return {
   ACTIONFAIL =
      {
         SHAVE =
            {
               AWAKEBEEFALO = "I don't think I can get away with that.",
               GENERIC = "I can't just shave whatever.",
               NOBITS = "There isn't anything left to shave.",
            },
         STORE =
            {
               GENERIC = "I don't think that'll work.",
               NOTALLOWED = "That doesn't fit in there.",
            },
      },
   ACTIONFAIL_GENERIC = "Whoops, that won't do. What was I thinking?",
   ANNOUNCE_ADVENTUREFAIL = "Well, that didn't go according to plan.",
   ANNOUNCE_BEES = "OH GOD NO, NOT THE BEES!",
   ANNOUNCE_BOOMERANG = "Ouch! How did that even hit me?",
   ANNOUNCE_HOT = "My lungs are burning!",
   ANNOUNCE_BURNT = "Yowch! This hurts!",
   ANNOUNCE_CHARLIE = "My head feels like it's going to explode!\nI- I'm going mad.",
   ANNOUNCE_CHARLIE_ATTACK = "OUCH! STOP THAT! WHERE ARE YOU?!", 
   ANNOUNCE_COLD = "It's so c-cold. W-what I wouldn't d-do for a kotatsu right now.",
   ANNOUNCE_CRAFTING_FAIL = "I can't make this work. I need all the components.",
   ANNOUNCE_DEERCLOPS = "This sound can only mean one thing...",
   ANNOUNCE_DUSK = "I'm getting sleepy.\nWhere's my bed?",
   ANNOUNCE_EAT =
      {
         GENERIC = "Delicious!",
         PAINFUL = "Oh god, what the hell did I eat?",
         SPOILED = "Why did I eat that?!",
         STALE = "Tastes as if it had been in a fridge for a month.\nWhich is to say, pretty bad.",
      },
   ANNOUNCE_DAMP = "It's getting moist.",
   ANNOUNCE_WET = "These clothes take forever to dry.\nI'll freeze like this!",
   ANNOUNCE_WETTER = "Everything feels heavy and cold.",
   ANNOUNCE_SOAKED = "I didn't think it would be possible to get any more soaked, but here we are.",
   ANNOUNCE_TOOL_SLIP = "Damn, I slipped!",
   ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "Deary me! That was lucky!",
   ANNOUNCE_SHELTER = "Finally a roof over my head. Is this what the cats felt like when they found Mayohiga?",
   ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "Not even Sherlock Holmes could find a trail in this.",
   ANNOUNCE_NODANGERSIESTA = "I can't take a nap with all this ruckus!",
   ANNOUNCE_NONIGHTSIESTA = "I'd love to take a nap, but missing out on the day would be a really bad idea.",
   ANNOUNCE_NONIGHTSIESTA_CAVE = "I refuse to sleep with bats and spiders.",
   ANNOUNCE_NOHUNGERSIESTA = "I need a snack first.",
   ANNOUNCE_NODANGERSLEEP = "I don't think this is a good idea.",
   ANNOUNCE_NODAYSLEEP = "I'm not tired quite yet.",
   ANNOUNCE_NODAYSLEEP_CAVE = "I refuse to sleep with bats and spiders.",
   ANNOUNCE_NOHUNGERSLEEP = "I'd love to sleep, but I might starve if I did that.",
   ANNOUNCE_ENTER_DARK = "I can't see anywhere without the moon.",
   ANNOUNCE_ENTER_LIGHT = "Finally some light!",
   ANNOUNCE_FREEDOM = "I made it! I'm finally free!",
   ANNOUNCE_HIGHRESEARCH = "No problem for a mind like mine.",
   ANNOUNCE_HOUNDS = "I've got a bad feeling about this.",
   ANNOUNCE_HUNGRY = "Where's Ran when you need her?",
   ANNOUNCE_HUNT_BEAST_NEARBY = "There you are.",
   ANNOUNCE_HUNT_LOST_TRAIL = "Wait, where did it go?",
   ANNOUNCE_INV_FULL = "I can only carry so much.",
   ANNOUNCE_KNOCKEDOUT = "...Oof.",
   ANNOUNCE_LOWRESEARCH = "Well that was a pointless waste of time.",
   ANNOUNCE_MOSQUITOS = "Stupid mosquitos!",
   ANNOUNCE_NO_TRAP = "Simple enough.",
   ANNOUNCE_PECKED = "Gah! If only I had my shikigami crows!",
   ANNOUNCE_QUAKE = "This does not bode well.",
   ANNOUNCE_RESEARCH = "Interesting.",
   ANNOUNCE_THORNS = "Ow!",
   ANNOUNCE_TORCH_OUT = "Well...",
   ANNOUNCE_TRAP_WENT_OFF = "Ah!",
   ANNOUNCE_UNIMPLEMENTED = "Hrm, I don't think this is finished quiet yet.",
   ANNOUNCE_WORMHOLE = "Where am I?",
   ANNOUNCE_CANFIX = "I should be able to repair this.",
   ANNOUNCE_ACCOMPLISHMENT = "Great!",
   ANNOUNCE_ACCOMPLISHMENT_DONE = "Hah, no problem.",
   BATTLECRY =
      {
         GENERIC = "You shall regret this!",
         PIG = "There is no place for you in this world!",
         PREY = "Die!",
         SPIDER = "A newspaper whack is all it takes to take care of you!",
         SPIDER_WARRIOR = "Ouh, figured out new tricks, have we?",
      },
   COMBAT_QUIT =
      {
         GENERIC = "Ah, I'm bored of this.",
         PIG = "You won't find your way into Gensokyou either way...",
         PREY = "... or perhaps I should just take a nap.",
         SPIDER = "I'll send Ran to take care of you later...",
         SPIDER_WARRIOR = "Fine, be like that.",
      },
   EAT_FOOD =
      {
      },
   DESCRIBE_GENERIC = "I can't think of anything noteworthy to say about this.",
   DESCRIBE_TOODARK = "Who's there?!",
   DESCRIBE_SMOLDERING = "Oh dear, this is not going to end well..",
   DESCRIBE =
      {
         PAPER_FAN = "My trusty fan.",
         ICEHAT = "Chilly.",
         MOLE =
            {
               UNDERGROUND = "These buggers keep on messing up our backyard.",
               ABOVEGROUND = "Stay away from my yard!",
            },
         MOLEHILL = "Usually Ran takes care of these.",
         MOLEHAT = "Innovative.",
         WEBBERSKULL = "I don't think I saw this in any textbook before.",
         GLOMMER = "It's a miracle this thing can fly.",
         GLOMMERFLOWER = "Would make a pretty hair accessory.",
         GLOMMERWINGS = "I doubt that these are actually what make Glommer fly.",
         GLOMMERFUEL = "Ick.",
         BELL = "Ringing it produces an ominous and powerful sound.",
         STATUEGLOMMER = 
            {
               GENERIC = "I wonder who built this.",
               EMPTY = "The statue seems to have something else to it...",
            },
         WORMLIGHT = "Nature sure is fascinating.",
         WORM =
            {
               PLANT = "Something is off about this...",
               DIRT = "This patch seems dug up.",
               WORM = "WHOAH!",
            },
         EEL = "These seem valuable.",
         EEL_COOKED = "Hmm. Not bad.",
         UNAGI = "Almost as good as Ran makes it.",
         EYETURRET = "The mind boggles at the possibilities.",
         EYETURRET_ITEM = "I still can't quite believe this exists.",
         MINOTAURHORN = "Spiky.",
         MINOTAURCHEST = "Looks like something out of a movie.",
         THULECITE_PIECES = "It feels very malleable.",
         POND_ALGAE = "All sorts of things grow in there.",
         GREENSTAFF = "Marisa would love to get her grubby little fingers on this.",
         POTTEDFERN = "I always considered myself pretty good at interior decoration.",
         THULECITE = "A strange alloy. I don't think I've seen the likes on earth.",
         ARMORRUINS = "It looks very sturdy and comfortable at the same time.",
         RUINS_BAT = "This will land a hefty hit.",
         RUINSHAT = "It's a bit too flashy for my tastes.",
         NIGHTMARE_TIMEPIECE =
            {
               CALM = "Seems to be all right at the moment.",
               WARN = "It's picking up some strong signals.",
               WAXING = "Looks like it's getting stronger.",
               STEADY = "I can't make up any change.",
               WANING = "Ah, now it's getting weaker again.",
               DAWN = "It's soon going to be all over.",
               NOMAGIC = "Absolutely nothing here.",
            },
         BISHOP_NIGHTMARE = "Oh no, I don't want to lose another play!",
         ROOK_NIGHTMARE = "Oh dear, it's as quick as in the game!",
         KNIGHT_NIGHTMARE = "I like chess, but not like this!",
         MINOTAUR = "The Greeks knew their stuff.",
         SPIDER_DROPPER = "As if regular spiders weren't bad enough already.",
         NIGHTMARELIGHT = "Ominous.",
         GREENGEM = "Feels as if a current was going through it.",
         RELIC = "Not my style.",
         RUINS_RUBBLE = "I should be able to put this back together.",
         MULTITOOL_AXE_PICKAXE = "Two in one, what a deal.",
         ORANGESTAFF = "My gaps are better than this thing.",
         YELLOWAMULET = "Feels soothing in a way.",
         GREENAMULET = "A handy catalyst.",
         SLURPERPELT = "It feels rather fuzzy.",
         SLURPER = "Deceptively cute.",
         SLURPER_PELT = "It feels rather fuzzy.",
         ARMORSLURPER = "Feels warm.",
         ORANGEAMULET = "Finally something to relieve my back.",
         YELLOWSTAFF = "The power of the stars under my command.",
         YELLOWGEM = "All these gems seem to be infused with power.",
         ORANGEGEM = "Pretty!",
         TELEBASE = 
            {
               VALID = "Looks good to go!",
               GEMS = "I don't think it has enough juice yet.",
            },
         GEMSOCKET = 
            {
               VALID = "All set.",
               GEMS = "It's empty.",
            },
         STAFFLIGHT = "I don't think I should get too close to that.",
         RESEARCHLAB4 = "Is this really magic, or all just trickery?",         
         ANCIENT_ALTAR = "That looks even older than me.",
         ANCIENT_ALTAR_BROKEN = "Useless.",
         ANCIENT_STATUE = "Is that... a person?",
         LICHEN = "Gross.",
         CUTLICHEN = "Icky, but might be edible.",
         CAVE_BANANA = "I bet the people from hell would get a kick out of this.",
         CAVE_BANANA_COOKED = "Smells better than most of the things I've been eating so far.",
         CAVE_BANANA_TREE = "Fruit that grows in a cave?",
         ROCKY = "A rock creature?",         
         COMPASS =
            {
               GENERIC="It doesn't seem to be oriented anywhere.",
               N = "North",
               S = "South",
               E = "East",
               W = "West",
               NE = "Northeast",
               SE = "Southeast",
               NW = "Northwest",
               SW = "Southwest",
            },
         HOUNDSTOOTH="Sharp.",
         ARMORSNURTLESHELL="Chen would love one of these.",
         BAT="Gah, I hope they don't get in my hair.",
         BATBAT = "I'm sure I could scare Remilia with this one.",
         BATWING="Reminds me of a certain vampire.",
         BATWING_COOKED="... alright.",
         BEDROLL_FURRY="Not quite a bed, but comfortable enough.",
         BUNNYMAN="Is this the lunarian's doing?",
         FLOWER_CAVE="Nature is amazing.",
         FLOWER_CAVE_DOUBLE="Nature is amazing.",
         FLOWER_CAVE_TRIPLE="Nature is amazing.",
   -- HERE
         GUANO="Messy creatures.",
         LANTERN="At least it won't get ash everywhere.",
         LIGHTBULB="Not irradiated, I hope.",
         MANRABBIT_TAIL="Would make a good earmuff.",
         MUSHTREE_TALL  ="I can't tell if this is a tree or a mushroom.",
         MUSHTREE_MEDIUM="Can't imagine they're less toxic when they're bigger.",
         MUSHTREE_SMALL ="Koishi would want to live in one of these.",
         RABBITHOUSE=
            {
               GENERIC = "Koishi would think to taste it.",
               BURNT = "If it was edible before, it's not now.",
            },
         SLURTLE="It seems mostly mindless. And slightly rude.",
         SLURTLE_SHELLPIECES="Looks like someone dropped a vase.",
         SLURTLEHAT="Ech, there's still slime in this.",
         SLURTLEHOLE="I can hear the hive. They're talking about rocks.",
         SLURTLESLIME="Like mucus, but more oily. Still disgusting.",
         SNURTLE="This one is still mindless, but more...twitchy.",
         SPIDER_HIDER="They don't want to get hurt.",
         SPIDER_SPITTER="The spiders are much ruder here!",
         SPIDERHOLE="Sounds like their hive. I hear random bits and pieces.",
         STALAGMITE="These stalgmites are shaped oddly.",
         STALAGMITE_FULL="These stalagmites are shaped oddly.",
         STALAGMITE_LOW="These stalagmites are shaped oddly.",
         STALAGMITE_MED="These stalagmites are shaped oddly.",
         STALAGMITE_TALL="These stalagmites are shaped oddly.",
         STALAGMITE_TALL_FULL="These stalagmites are shaped oddly.",
         STALAGMITE_TALL_LOW="These stalagmites are shaped oddly.",
         STALAGMITE_TALL_MED="These stalagmites are shaped oddly.",

         TURF_CARPETFLOOR = "Ground is for walking, not holding.",
         TURF_CHECKERFLOOR = "Ground is for walking, not holding.",
         TURF_DIRT = "Ground is for walking, not holding.",
         TURF_FOREST = "Ground is for walking, not holding.",
         TURF_GRASS = "Ground is for walking, not holding.",
         TURF_MARSH = "Ground is for walking, not holding.",
         TURF_ROAD = "Instant road, just add ground.",
         TURF_ROCKY = "Ground is for walking, not holding.",
         TURF_SAVANNA = "Ground is for walking, not holding.",
         TURF_WOODFLOOR = "I hope it's smooth enough, my slippers will get snagged.",

         TURF_CAVE="Yet another ground type.",
         TURF_FUNGUS="Yet another ground type.",
         TURF_SINKHOLE="Yet another ground type.",
         TURF_UNDERROCK="Yet another ground type.",
         TURF_MUD="Yet another ground type.",
         
         TURF_DECIDUOUS = "Yet another ground type.",
         TURD_SANDY = "Yet another ground type.",
         TURF_BADLANDS = "Yet another ground type.",
         BEARGER = "Why are they always so hungry?!",
         BEARGERVEST = "It's so hot in this!",
         ICEPACK = "Holds in hot as well as cold.",
         BEARGER_FUR = "A mat of thick fur.",

         POWCAKE = "Lasts forever. Almost long enough to find someone who'd want to eat it.",
         CAVE_ENTRANCE = 
            {
               GENERIC="Is that..?",
               OPEN = "Ah, the underground. Reminds me of home.",
            },
         CAVE_EXIT = "I suppose I could always go back up...",
         MAXWELLPHONOGRAPH = "How obnoxious.",
         BOOMERANG = "Is there magic that makes it come back?",
         PIGGUARD = "At least they have a reason to be hostile. Somewhat.",
         ABIGAIL = "Awww, she has a cute little bow.",
         ADVENTURE_PORTAL = "Could Koishi have come here..?",
         AMULET = "The magic radiating from this feels...soothing.",
         ANIMAL_TRACK = "Tracks from a gentle giant.",
         ARMORGRASS = "How is this even considered protection?",
         ARMORMARBLE = "Slightly worse than metal, but just as heavy.",
         ARMORWOOD = "I'm going to get a sliver from this.",
         ARMOR_SANITY = "I'm starting to feel sick in this.",
         ASH =
            {
               GENERIC = "Dusty.",
               REMAINS_EYE_BONE = "The eyebone was consumed by fire when I teleported!",
               REMAINS_THINGIE = "This was once some thing before it got burned...",
            },
         AXE = "A stick and a rock. How sophisticated.",
         BABYBEEFALO = "Ahh, new life...",
         BACKPACK = "Now I don't have to hold everything.",
         BACONEGGS = "Okuu would be begging for scraps by now.",
         BANDAGE = "Koishi would spend all day licking this.",
         BASALT = "Basalt. Much denser than usual.",
         BATBAT = "Odd, yet effective.",
         BEARDHAIR = "Could a rabbit even make this..?",
         BEDROLL_STRAW = "Better than sleeping on the ground, but only just.",
         BEE =
            {
               GENERIC = "A diligent little fellow. No mind, though.",
               HELD = "Hold still, child, I'll let you go soon.",
            },
         BEEBOX =
            {
               FULLHONEY = "What an effective workforce.",
               GENERIC = "Now everyone can appreciate your new home.",
               NOHONEY = "It's empty.",
               SOMEHONEY = "The hive has been working, I see.",
               BURNT = "Oh dear.",
            },
         BEEFALO =
            {
               FOLLOWER = "It thinks I'm the herd leader.",
               GENERIC = "A loyal, nurturing soul. It wants to have a family.",
               NAKED = "Poor thing. I hope it grows back soon.",
               SLEEPING = "They snore almost as loudly as Koishi.",
            },
         BEEFALOHAT = "I still feel bad about this.",
         BEEFALOWOOL = "Ech. These things need a proper bath.",
         BEEHAT = "Bees can get a bit...touchy.",
         BEEHIVE = "I hope Koishi didn't try sticking her hand in there.",
         BEEMINE = "This feels cruel.",
         BEEMINE_MAXWELL = "It makes the most annoying sound.",
         BERRIES = "Tastes fine, but stains terribly.",
         BERRIES_COOKED = "Still tastes alright.",
         BERRYBUSH =
            {
               BARREN = "Never was much of a gardener...",
               GENERIC = "Well, at least I know what Koishi is living off of.",
               PICKED = "They'll grow back eventually.",
               WITHERED = "Plants are so finicky.",
            },
         BIRDCAGE =
            {
               GENERIC = "A home for a bird friend.",
               OCCUPIED = "Hello there, how are you feeling?",
               SLEEPING = "Shhh.",
            },
         BIRDTRAP = "I hope they don't thrash around and hurt themselves in this.",
         BIRD_EGG = "It's a bit cold. I don't think it will hatch.",
         BIGFOOT = "A sapient foot. Stranger things have happened.",
         BONESHARD = "Kasha were never so messy.",
         BUZZARD = "Hello. No, I am quite well, thank you.",
         CACTUS = 
            {
               GENERIC = "No need to be so prickly.",
               PICKED = "I didn't expect it to deflate.",
            },
         CACTUS_MEAT_COOKED = "At least the spines burned off.",
         CACTUS_MEAT = "This seems dangerous.",
         CACTUS_FLOWER = "Spines on flowers? This almost reminds me of home...",

         COLDFIRE =
            {
               EMBERS = "Does it take...wood? Or...",
               GENERIC = "This must be magic. It must be!",
               HIGH = "This is so wrong.",
               LOW = "It's getting...warmer? Um.",
               NORMAL = "This must be magic. It must be!",
               OUT = "I don't even know.",
            },
         CATCOON = "Cats are just like children.",
         CATCOONDEN = 
            {
               GENERIC = "Ooh, what a cozy home.",
               EMPTY = "Hm. No one's home.",
            },
         CATCOONHAT = "I don't feel well.",
         WATERMELON_SEEDS = "It's a seed.",
         EYEBRELLAHAT =	"Gross to make, but oddly effective.",
         BIRD_EGG_COOKED = "Okuu's egg senses are probably tingling.",
         BISHOP = "I thought science was detrimental to faith.",
         BLOWDART_FIRE = "The next best thing to a fire spell.",
         BLOWDART_SLEEP = "Enforced sweet dreams.",
         BLOWDART_PIPE = "Good practice for my birthday cake!",
         BLUEAMULET = "Good for countering the summer heat, I guess.",
         BLUEGEM = "Hm. Do you suppose this is magical?",
         BLUEPRINT = "Designs of some kind.",
         BLUE_CAP = "Smells strange, but apparently healthy.",
         BLUE_CAP_COOKED = "Still smells strange.",
         BLUE_MUSHROOM =
            {
               GENERIC = "It's a mushroom.",
               INGROUND = "Hm. Maybe later.",
               PICKED = "It should grow back eventually.",
            },
         BOARDS = "Rugged, but durable.",
         BOAT = "Is that how I got here?",
         BONESTEW = "Enough for two...",
         BUGNET = "For catching insects, not insect youkai.",
         BUSHHAT = "Is there something moving in this?",
         BUTTER = "Hahaha...No.",
         BUTTERFLY =
            {
               GENERIC = "So dainty and graceful.",
               HELD = "Don't touch the wings! They're delicate.",
            },
         BUTTERFLYMUFFIN = "This looks only slightly disgusting.",
         BUTTERFLYWINGS = "It's just an insect, I guess...",
         CAMPFIRE =
            {
               EMBERS = "It's going to go out at this rate.",
               GENERIC = "Sure beats darkness.",
               HIGH = "I saw bigger fires back at home.",
               LOW = "Hm. Needs fuel.",
               NORMAL = "Cozy.",
               OUT = "On we go, I suppose.",
            },
         CANE = "How does this make walking any faster?",
         CARROT = "A bit dirty, but good for you.",
         CARROT_COOKED = "Easy to hide in eggs, so certain ravens get their vegetables.",
         CARROT_PLANTED = "I think that's a carrot.",
         CARROT_SEEDS = "Seeds. The birds would appreciate these.",
         CAVE_FERN = "Cave ferns.",
         CHARCOAL = "Corpses are much better for fueling fires. Less waste.",
         CHESSJUNK1 = "A pile of broken chess pieces.",
         CHESSJUNK2 = "Another pile of broken chess pieces.",
         CHESSJUNK3 = "Even more broken chess pieces.",
         CHESTER = "Interesting! This fellow is of noble blood.",
         CHESTER_EYEBONE =
            {
               GENERIC = "Peekaboo.",
               WAITING = "I can see its eye twitching beneath the eyelid.",
            },
         COOKEDMANDRAKE = "Poor little thing.",
         COOKEDMEAT = "*sigh*",
         COOKEDMONSTERMEAT = "Still smells like suphur.",
         COOKEDSMALLMEAT = "It wouldn't want to go to waste...",
         COOKPOT =
            {
               COOKING_LONG = "A watched pot never boils.",
               COOKING_SHORT = "Nearly meal time.",
               DONE = "It feels odd not tripping over Kashas right about now.",
               EMPTY = "What sounds good right now?",
            },
         CORN = "One of the less difficult vegetables to feed the littluns.",
         CORN_COOKED = "If only I had one of those 'movies' to watch.",
         CORN_SEEDS = "It's a seed.",
         CROW =
            {
               GENERIC = "He's smaller than a Hell Raven.",
               HELD = "He's not very happy in there.",
            },
         CUTGRASS = "Flexible yet sturdy.",
         CUTREEDS = "How does this make paper?",
         CUTSTONE = "Perfectly smooth.",
         DEADLYFEAST = "A most potent dish.",
         DEERCLOPS = "Its mind is polluted with rage and hunger!",
         DEERCLOPS_EYEBALL = "I wonder how long it had been suffering.",
         DEPLETED_GRASS =
            {
               GENERIC = "Grass, I think.",
            },
         DEVTOOL = "It smells of bacon!",
         DEVTOOL_NODEV = "I'm not strong enough to wield it.",
         DIRTPILE = "Are those footprints?",
         DIVININGROD =
            {
               COLD = "Nothing.",
               GENERIC = "If only it could be set for people...",
               HOT = "I'm right on top of something!",
               WARM = "I'm getting warm.",
               WARMER = "Warmer still!",
            },
         DIVININGRODBASE =
            {
               GENERIC = "Do you fit something in this?",
               READY = "It's pulsating. I think something has to go here.",
               UNLOCKED = "I guess that did it.",
            },
         DIVININGRODSTART = "Is this some Outside machine?",
         DRAGONFRUIT = "What a weird fruit.",
         DRAGONFRUIT_COOKED = "It smells very sweet.",
         DRAGONFRUIT_SEEDS = "It's a seed.",
         DRAGONPIE = "A pie? Seriously?",
         DRUMSTICK = "The poor thing...it wanted to be helpful.",
         DRUMSTICK_COOKED = "At least it won't go to waste...",
         DUG_BERRYBUSH = "I should plant this.",
         DUG_GRASS = "I should plant this.",
         DUG_MARSH_BUSH = "I should plant this.",
         DUG_SAPLING = "I should plant this.",
         DURIAN = "It smells terrible.",
         DURIAN_COOKED = "Ugh, now it stinks even more!",
         DURIAN_SEEDS = "It's a seed.",
         EARMUFFSHAT = "I have to stay warm...",
         EGGPLANT = "What a silly name.",
         EGGPLANT_COOKED = "Not even slightly egg-like.",
         EGGPLANT_SEEDS = "It's a seed.",
         EVERGREEN =
            {
               BURNING = "I hope there were no nests in there...",
               BURNT = "Fire feeds fire...and who shall stop the burning?",
               CHOPPED = "It would have made a poor roost anyway.",
               GENERIC = "Too bristly. Koishi wouldn't want to climb it.",
            },
         EVERGREEN_SPARSE =
            {
               BURNING = "I hope there were no nests in there...",
               BURNT = "Fire feeds fire...and who shall stop the burning?",
               CHOPPED = "It would have made a poor roost anyway.",
               GENERIC = "I think it's dying.",
            },
         EYEPLANT = "That's not even slightly conspicuous.",
         FARMPLOT =
            {
               GENERIC = "I should try planting some crops.",
               GROWING = "It's working, right?",
               NEEDSFERTILIZER = "I think it needs to be fertilized.",
               BURNT = "How embarassing."
            },
         FEATHERHAT = "The birds feel comforted by this, for some reason.",
         DRAGONFLY = "It likes fire far, far too much.",
         ARMORDRAGONFLY = "Stop, I'm not flammable! I'm not!",
         DRAGON_SCALES = "Its very hide is magical.",
         DRAGONFLYCHEST = "Fireproof. Perfect.",
         DECIDUOUSTREE = 
            {
               BURNING = "Such a waste.",
               BURNT = "At least nothing lived in it.",
               CHOPPED = "Perhaps something can find shelter in this.",
               POISON = "Why are all the trees here so angry?!",
               GENERIC = "These are much better for climbing.",
            },
         ACORN = 
            {
               GENERIC = "Hm. I wonder if it's edible.",
               PLANTED = "It'll be a tree soon.",
            },
         ACORN_COOKED = "It smells wonderful.",
         BIRCHNUTDRAKE = "Gah! Vicious little things!",
         LAVASPIT = 
            {
               HOT = "Molten...something. Too hot!",
               COOL = "I think it's cool now?",
            },
         FEATHER_CROW = "Poor thing.",
         FEATHER_ROBIN = "Poor thing.",
         FEATHER_ROBIN_WINTER = "Poor thing.",
         FEM_PUPPET = "Her mind is brimming with terror...I have to do something.",
         FIREFLIES =
            {
               GENERIC = "Koishi would chase these all night.",
               HELD = "A jar would be cruel. A pocket is much better.",
            },
         FIREHOUND = "Red...an alpha, maybe?",
         FIREPIT =
            {
               EMBERS = "It's going to go out at this rate.",
               GENERIC = "Sure beats darkness.",
               HIGH = "I saw bigger fires back at home.",
               LOW = "Hm. Needs fuel.",
               NORMAL = "Cozy.",
               OUT = "The camp is ready, just needs a fire.",
            },
         FIRESTAFF = "No mage would be caught dead with this thing.",

         FISH = "Now I shall eat for a day.",
         FISHINGROD = "I hope this doesn't annoy a lake spirit or something.",
         FISHSTICKS = "Like fish regular, but in sticks.",
         FISHTACOS = "This feels a bit western.",
         FISH_COOKED = "The ribs always stick in my teeth.",
         FLINT = "Sharp. Good for tools, maybe.",
         FLOWER = "A rose by another name...",
         FLOWERHAT = "Koishi and I would always weave these together in the garden.",
         FLOWER_EVIL = "I get dizzy if I look at it for too long.",
         FOLIAGE = "Some leafy greens.",
         FOOTBALLHAT = "Safety first and such.",
         FROG =
            {
               DEAD = "Crude little creature.",
               GENERIC = "I didn't expect it to have such bitter thoughts.",
               SLEEPING = "At least their dreams are peaceful.",
            },
         FROGGLEBUNWICH = "At least the other things cover up the frog taste.",
         FROGLEGS = "Don't let them fool you, this is no delicacy.",
         FROGLEGS_COOKED = "Clearly frogs weren't made to be edible.",
         FRUITMEDLEY = "Mmm, fruity.",
         GEARS = "A kappa might make more sense out of these.",
         GHOST = "It's more vengeful than it is afraid!",
         GOLDENAXE = "I can't help but feel pompous with this.",
         GOLDENPICKAXE = "This seems a bit counter-intuitive.",
         GOLDENPITCHFORK = "Why did I even make a pitchfork this fancy?",
         GOLDENSHOVEL = "How flamboyant.",
         GOLDNUGGET = "The lengths man would brave for a fleck of gold...",
         GRASS =
            {
               BARREN = "Isn't brown grass just dormant?",
               BURNING = "That's burning fast!",
               GENERIC = "Field grass.",
               PICKED = "This should grow back fairly soon.",
               WITHERED = "Too hot for even the grasses.",
            },
         GREEN_CAP = "Sniffing it makes me nauseous.",
         GREEN_CAP_COOKED = "It smells like burnt chicken.",
         GREEN_MUSHROOM =
            {
               GENERIC = "A mushroom of some kind.",
               INGROUND = "Later, maybe.",
               PICKED = "It should grow back.",
            },
         GUNPOWDER = "The Outside would wage brutal wars with this.",
         HAMBAT = "I don't know why this seemed like a good idea.",
         HAMMER = "A better tool than a cudgel, admittedly.",
         HEALINGSALVE = "The stinging means that it's working.",
         HEATROCK =
            {
               FROZEN = "As cool as Hell is hot.",
               COLD = "Cold, like a regular stone.",
               GENERIC = "Stones hold temperature rather well.",
               HOT = "The glow is nostalgic.",
               WARM = "It's warm and pleasant to the touch.",
            },
         HOME = "Hello? Koishi?",
         HOMESIGN = 
            {
               GENERIC = "I wonder if Koishi would read this.",
               BURNT = "Now no one can read it!"
            },
         HONEY = "This supposedly never goes bad.",
         HONEYCOMB = "Seems rather cramped to live in.",
         HONEYHAM = "The honey doesn't make it any less gruesome.",
         HONEYNUGGETS = "I wonder if this is even good for you?",
         HORN = "I can actually hear the ocean in this thing.",
         HOUND = "It's too sadistic to be a normal animal.",
         HOUNDBONE = "Haunting.",
         HOUNDMOUND = "I hear Hounds in there. They can sense my presence.",
         ICEBOX = "But there's no magic in it! How does it stay cold?",
         ICEHOUND = "Its winter coat does nothing to hide its brutality.",
         INSANITYROCK =
            {
               ACTIVE = "I want to break it and I don't know why.",
               INACTIVE = "I can't feel any magic, but these inscriptions give me a bad feeling.",
            },
         JAMMYPRESERVES = "Sweet and all natural.",
         LIGHTNINGGOAT = 
            {
               GENERIC = "They're...'quirky.'",
               CHARGED = "Ah, that one is mad. Very mad.",
            },
         LIGHTNINGGOATHORN = "The ends spark occasionally.",
         GOATMILK = "...I guess that one was female?",
         KABOBS = "Seems like good camping food.",
         KILLERBEE =
            {
               GENERIC = "Their name is very appropriate!",
               HELD = "It's thrashing fairly violently. I should get rid of this...",
            },
         KNIGHT = "What in the world is that? A machine?",
         KOALEFANT_SUMMER = "Aw, it's lonely! He just wants a friend.",
         KOALEFANT_WINTER = "Aw, it's lonely! He just wants a friend.",
         KRAMPUS = "'Wicked'? No, no! You've got it all wrong-!",
         KRAMPUS_SACK = "The sack of a vengeful thief.",
         LEIF = "'Murderer'? But how could I have known?!",
         LEIF_SPARSE = "'Murderer'? But how could I have known?!",
         LIGHTNING_ROD =
            {
               CHARGED = "Is this how the Outside world powers their machines?",
               GENERIC = "I saw a kappa device like this once.",
            },
         LITTLE_WALRUS = "That child is disturbed.",
         LIVINGLOG = "I feel like it's judging me.",
         LOCKEDWES = "Is that a human? He thinks he's trapped.",
         LOG =
            {
               BURNING = "It would have burnt better in a fireplace.",
               GENERIC = "This wood isn't very high quality.",
            },
         LUREPLANT = "What in the world?",
         LUREPLANTBULB = "What a bizarre plant.",
         MALE_PUPPET = "His mind is brimming over with terror...I have to do something.",
         MANDRAKE =
            {
               DEAD = "I don't know if I should feel bad or not.",
               GENERIC = "I think that plant just moved",
               PICKED = "A...plant friend?",
            },
         MANDRAKESOUP = "I cooked it myself!",
         MANDRAKE_COOKED = "Its face makes me uncomfortable.",
         MARBLE = "Beautiful marble. Makes lovely decoration.",
         MARBLEPILLAR = "This seems somewhat out of place.",
         MARBLETREE = "I can't tell if this is carved or just formed that way.",
         MARSH_BUSH =
            {
               BURNING = "Watch for burning thorns!",
               GENERIC = "A somewhat cruel gnarl of thorns.",
               PICKED = "My fingers still hurt from that.",
            },
         MARSH_PLANT = "Some marsh plant.",
         MARSH_TREE =
            {
               BURNING = "Oh my, it burns spectacularly!",
               BURNT = "Some of the thorns are still glowing.",
               CHOPPED = "A bit less unnerving now.",
               GENERIC = "A wicked-looking tree. I think it's dead.",
            },
         MAXWELL = "A tragically twisted, wicked soul. It's sad, really.",
         MAXWELLHEAD = "I can see into his pores.",
         MAXWELLLIGHT = "How very ominous.",
         MAXWELLLOCK = "Looks almost like a key hole.",
         MAXWELLTHRONE = "How very ominous.",
         MEAT = "...I don't want to think about it.",
         MEATBALLS = "Simple but filling.",
         MEATRACK =
            {
               DONE = "It looks dried to me.",
               DRYING = "The way it gently sways is kind of hypnotic.",
               GENERIC = "Meat lasts longer this way.",
               DRYINGINRAIN = "Oh bother, now it's all wet.",
               BURNT = "That's a bit TOO dry."
            },
         MEAT_DRIED = "Smells like smoke.",
         FLOWERSALAD = "Nature's dish.",
         ICECREAM = "Delicious. Koishi would love this.",
         WATERMELONICLE = "Ah, this takes me back.",
         TRAILMIX = "Something to munch on the road.",
         HOTCHILI = "Oh wow, this has some kick to it.",
         GUACAMOLE = "How disturbing.",
         MOOSE = "Oh.",
         MOOSEEGG = "It's...sparking.",
         MOSSLING = "I have such mixed feelings right now.",
         FEATHERFAN = "Ah, what a lovely breeze.",
         GOOSE_FEATHER = "I can see Koishi curling up in these.",
         STAFF_TORNADO = "Spinning doom.",
         MERM = "They hate everything else as well. A small improvement.",
         MERMHEAD = "Is there a sort of war going on?",
         MERMHOUSE = "I think something slithered through past the window just now.",
         MINERHAT = "Perfect for spelunking.",
         MONKEY = "Impish and flighty. Who does that remind you of?",
         MONKEYBARREL = "This feels like a bad pun.",
         MONSTERLASAGNA = "Like normal food, but more poisonous.",
         MONSTERMEAT = "Toxic meat from toxic creatures. Fitting.",
         MONSTERMEAT_DRIED = "Did the drying even change anything?",
         MOSQUITO =
            {
               GENERIC = "Senseless little bloodsucker.",
               HELD = "That beak's like a syringe!",
            },
         MOSQUITOSACK = "This seems like it would make you very sick.",
         MOUND =
            {
               DUG = "That was horribly disrespectful.",
               GENERIC = "I normally wouldn't dare, but times are desperate...",
            },
         NIGHTLIGHT = "I don't like the way it glows.",
         NIGHTMAREFUEL = "When I touch it, it tries to shy away.",
         NIGHTSWORD = "This is just as dangerous to hold as it is to be hit with!",
         NITRE = "Is this sulphur? Or something else?",
         ONEMANBAND = "How obnoxious.",
         PANDORASCHEST = "I read a story like this once...",
         PANFLUTE = "Music soothes even the most wicked of hearts.",
         PAPYRUS = "I never was one for keeping a diary.",
         PENGUIN = "A classy little fellow.\nIt wants a companion to travel afar with.",
         PERD = "It wants to be helpful. And berries.",
         PEROGIES = "Weird, but I guess it's edible.",
         PETALS = "She loves me, she loves me not...",
         PETALS_EVIL = "My hands are beginning to itch...",
         PICKAXE = "Rock breaks rock.",
         PIGGYBACK = "So they're useful for something after all.",
         PIGHEAD = 
            {	
               GENERIC = "How barbaric.",
               BURNT = "Ew.",
            },
         PIGHOUSE =
            {
               FULL = "He doesn't trust me.",
               GENERIC = "Figures a pig would live in a glorified outhouse.",
               LIGHTSOUT = "Hiding like a proper coward should.",
               BURNT = "...he at least got out, right?"
            },
         PIGKING = "A gluttonous bully.",
         PIGMAN =
            {
               DEAD = "Someone should tell his family.",
               FOLLOWER = "He's part of my entourage.",
               GENERIC = "'Monster', 'evil'...heard it all before.",
               GUARD = "He looks serious.",
               WEREPIG = "It's lost what little mind it had!",
            },
         PIGSKIN = "Is that a tail? Ew.",
         PIGTENT = "Smells like bacon.",
         PIGTORCH = "They think these keep the sun burning.",
         PINECONE = 
            {
               GENERIC = "These don't come from these kinds of trees, do they?",
               PLANTED = "If a tree sprouts in a forest...no, that's not right.",
            },
         PITCHFORK = "The mob weapon of choice.",
         PLANTMEAT = "Its sweet smell is almost overwhelming.",
         PLANTMEAT_COOKED = "It doesn't smell so good anymore.",
         PLANT_NORMAL =
            {
               GENERIC = "Leafy!",
               GROWING = "This is what humans do, right? Is it working?",
               READY = "I guess it's done growing.",
               WITHERED = "I'm really bad at this."
            },
         POMEGRANATE = "How exotic.",
         POMEGRANATE_COOKED = "Do they eat these in the Outside world?",
         POMEGRANATE_SEEDS = "It's a seed.",
         POND = "I wonder how far down it goes.",
         POOP = "Gross.",
         PUMPKIN = "The Outside world carves these for...something.",
         PUMPKINCOOKIE = "How did that whole pumpkin go into this?",
         PUMPKIN_COOKED = "They're better for eating than decoration.",
         PUMPKIN_LANTERN = "I forget which holiday this is for.",
         PUMPKIN_SEEDS = "It's a seed.",
         PURPLEAMULET = "I don't like the noises it makes.",
         PURPLEGEM = "I'm more of a pink person.",
         RABBIT =
            {
               GENERIC = "Hi little guy. Are you hungry?",
               HELD = "Shh, it's okay. Don't be afraid.",
            },
         RABBITHOLE = 
            {
               GENERIC = "I always wonder what these looked like inside.",
               SPRING = "I wonder where they go in spring.",
            },
         RAINOMETER = 
            {	
               GENERIC = "Why can't I just look up?",
               BURNT = "It was pointless anyway.",
            },
         RATATOUILLE = "Even the animals would like this.",
         RAINCOAT = "Always dress properly when it's sprinkling.",
         RAINHAT = "Cute! Koishi would look good in it.",
         RAZOR = "Why would I need this again?",
         REDGEM = "It feels magical, somewhat.",
         RED_CAP = "It makes my nose tingle.",
         RED_CAP_COOKED = "Now it just gives me a headache.",
         RED_MUSHROOM =
            {
               GENERIC = "It's a mushroom.",
               INGROUND = "Maybe later.",
               PICKED = "I think this will grow back.",
            },
         REEDS =
            {
               BURNING = "For marsh plants, those burn pretty well.",
               GENERIC = "Reeds and cattails. Perfect cat toys.",
               PICKED = "The Kasha would have devoured this in minutes.",
            },
         RELIC = 
            {
               GENERIC = "Leftovers from...something old, I suppose.",
               BROKEN = "Too aged to be useful.",
            },
         RUINS_RUBBLE = "Ruined nothings.",
         RUBBLE = "Just bits and pieces of rock.",
         RESEARCHLAB = 
            {	
               GENERIC = "This has nothing to do with science.",
               BURNT = "Awkward thing.",
            },
         RESEARCHLAB2 = 
            {
               GENERIC = "It still doesn't feel very scientific.",
               BURNT = "I'm surprised it was even flammable.",
            },
         RESEARCHLAB3 = 
            {
               GENERIC = "I feel like I've tapped into something...dark.",
               BURNT = "There's symbolism to be had here.",
            },
         RESEARCHLAB4 = 
            {
               GENERIC = "Someone feels very clever for this, somewhere.",
               BURNT = "That's what I think of your naming skills.",
            },
         RESURRECTIONSTATUE = 
            {
               GENERIC = "That's the crudest ward I've ever seen.",
               BURNT = "Oh, that's just asking for trouble.",
            },
         RESURRECTIONSTONE = "This relic stinks of black magic.",
         ROBIN =
            {
               GENERIC = "Hello there. Nice weather we're having?",
               HELD = "He seems very comfortable like this.",
            },
         ROBIN_WINTER =
            {
               GENERIC = "Poor thing is hungry.",
               HELD = "He thinks the warmth is heavenly.",
            },
         ROBOT_PUPPET = "What is this? Another machine?",
         ROCK_LIGHT =
            {
               GENERIC = "I wonder if this is connected to Old Hell...",
               OUT = "Looks fragile.",
               LOW = "The lava's crusting over.",
               NORMAL = "Nice and comfy.",
            },
         ROCK_ICE = 
            {
               GENERIC = "This ice is...strange.",
               MELTED = "At least Koishi could amuse herself.",
            },
         ROCK_ICE_MELTED = "At least Koishi could amuse herself.",
         ICE = "Don't break your teeth on this.",
         ROCK = "Hmm...not quite a little stone.",
         ROCKS = "I can't read their mind.",
         ROOK = "How can something so heavy carry itself so quickly?",
         ROPE = "Grass rope. More effective than it sounds.",
         ROTTENEGG = "This is why the ravens aren't allowed to stash food in their rooms.",
         SANITYROCK =
            {
               ACTIVE = "I thought I heard something. Is it making noises?",
               INACTIVE = "The top of it is just barely sticking out.",
            },
         SAPLING =
            {
               BURNING = "That's burning fast!",
               GENERIC = "What kind of tree is this?",
               PICKED = "I think it's dead.",
               WITHERED = "Even the trees can't stand the heat."
            },
         SEEDS = "Seeds. Birds like them.",
         SEEDS_COOKED = "Crunchy.",
         SEWING_KIT = "If I had a yen for every torn shirt I've patched...",
         SHOVEL = "A rock on a stick, but a very dig-y rock.",
         SILK = "Eh. The earth spiders weave it better.",
         SKELETON_PLAYER = "I hope Orin doesn't go after this one...",
         SKELETON = "Orin would like him.",
         SKULLCHEST = "This seems like a bad idea.",
         SMALLBIRD =
            {
               GENERIC = "Such a precious little thing.",
               HUNGRY = "Aw, are you hungry?",
               STARVING = "Poor thing is famished!",
            },
         SMALLMEAT = "This is horrible.",
         SMALLMEAT_DRIED = "It's dried out now.",
         SPEAR = "A rock on a stick. How ingenious.",
         SPIDER =
            {
               DEAD = "No contest.",
               GENERIC = "Spiders are one of the most common human fears.",
               SLEEPING = "They're actually kind of cute asleep.",
            },
         SPIDERDEN = "There's a trick to not getting stuck, so I'm told.",
         SPIDEREGGSACK = "I don't know whether to let it hatch or to burn it...",
         SPIDERGLAND = "I don't think this is the venom sac.",
         SPIDERHAT = "When I meet its gaze, I start to get a headache.",
         SPIDERQUEEN = "I feel a great vengefulness in this one.",
         SPIDER_WARRIOR =
            {
               DEAD = "Vicious thing.",
               GENERIC = "Its thoughts almost sound like...war chants.",
               SLEEPING = "I can't imagine it'd be a heavy sleeper.",
            },
         SPOILED_FOOD = "Disgusting.",
         REFLECTIVEVEST = "Well, at least she could see me.",
         HAWAIIANSHIRT = "Breezy.",
         STATUEHARP = "Why are statues always headless?",
         STATUEMAXWELL = "Oh for heaven's sake...",
         STINGER = "They die if they lose these, so I've heard.",
         STRAWHAT = "It makes me feel a little cheerful to wear this.",
         STUFFEDEGGPLANT = "At least its shape is good for something.",
         SUNKBOAT = "It's no use to me out there!",
         SWEATERVEST = "I feel like a businesswoman.",
         TAFFY = "Koishi always did have a sweet tooth.",
         TALLBIRD = "It trusts me, but only wants to raise its child.",
         TALLBIRDEGG = "The wonder of life...",
         TALLBIRDEGG_COOKED = "Necessary. It was necessary. It wasn't even alive yet...",
         TALLBIRDEGG_CRACKED =
            {
               COLD = "It's ice cold! It needs to get warmer.",
               GENERIC = "Take your time, little one.",
               HOT = "It's got to cool off.",
               LONG = "Take your time, little one.",
               SHORT = "I think it's ready to hatch anytime.",
            },
         TALLBIRDNEST =
            {
               GENERIC = "What a gorgeous shell.",
               PICKED = "I wonder if the mother is broody.",
            },
         TEENBIRD =
            {
               GENERIC = "They grow up so fast.",
               HUNGRY = "Ah yes, food. Let's find you something.",
               STARVING = "I know I know, you're hungry! Don't get cross at me.",
            },
         TELEBASE =
            {
               VALID = "I guess it's ready?",
               GEMS = "Maybe it needs gems.",
            },
         GEMSOCKET = 
            {
               VALID = "Looks ready.",
               GEMS = "It needs a gem.",
            },
         TELEPORTATO_BASE =
            {
               ACTIVE = "Something about this device makes me nervous.",
               GENERIC = "An altar? Or some kind of machine?",
               LOCKED = "Did I forget a piece?",
               PARTIAL = "What an awkward contraption.",
            },
         TELEPORTATO_BOX = "There's no magic and the box is empty. Where does the spark come from?",
         TELEPORTATO_CRANK = "It's unexpectedly durable.",
         TELEPORTATO_POTATO = "This thing feels unnatural.",
         TELEPORTATO_RING = "Some kind of magical focus?",
         TELESTAFF = "Flying is still better.",
         TENT = 
            {
               GENERIC = "At least it blocks the wind.",
               BURNT = "That could have been me!",
            },
         SIESTAHUT = 
            {
               GENERIC = "Blocks the sun, I suppose.",
               BURNT = "Oh dear. Too much sun?",
            },
         TENTACLE = "All I can hear is a distant, bottomless rage...",
         TRANSISTOR = "I have no idea what I'm doing.",
         TENTACLESPIKE = "It's all stiff and cold.",
         TUMBLEWEED = "Is that a bush?",
         GRASS_UMBRELLA = "This feels more desperate than anything.",
         WARG = "Oh good gracious, is it ever hungry.",
         WATERMELON = "It's been so long since I had some!",
         WATERMELON_COOKED = "I never thought to cook them, honestly.",
         WATERMELONHAT = "...this is stupid.",
         TENTACLESPOTS = "They smell strange. And...twitch.",
         TENTACLE_PILLAR = "The magnitude of this creature's anger is disturbing.",
         TENTACLE_PILLAR_ARM = "Are these newborn?!",
         TENTACLE_GARDEN = "The magnitude of this creature's anger is disturbing.",
         TOPHAT = "It feels refined, somehow.",
         TORCH = "Light is right.",
         TRAP = "To trap small things harmlessly.",
         TRAP_TEETH = "A cruel yet effective spring trap.",
         TRAP_TEETH_MAXWELL = "Watch your step.",
         TREASURECHEST = "A place to organize my belongings.",
         TREASURECHEST_TRAP = "How convenient!",
         TREECLUMP = "How annoying.",
         TRINKET_1 = "They must have endured extreme heat to melt like this.",
         TRINKET_10 = "False teeth. Ew.",
         TRINKET_11 = "Somehow I think it talks, but I must be imagining it.",
         TRINKET_12 = "There's something unsavory about this thing.",
         TRINKET_2 = "It looks like a toy. It doesn't work, though.",
         TRINKET_3 = "This knot is tied unusually tight.",
         TRINKET_4 = "I can feel its glassy eyes watching me when I look away.",
         TRINKET_5 = "I'm not sure what this is supposed to be.",
         TRINKET_6 = "This looks like part of a kappa device.",
         TRINKET_7 = "I think this is a toy.",
         TRINKET_8 = "Is this some kind of necklace? Or a plug?",
         TRINKET_9 = "I'm more of a zipper person, myself.",
         TRUNKVEST_SUMMER = "Have to stay warm...",
         TRUNKVEST_WINTER = "Have to stay warm...",
         TRUNK_COOKED = "I think I'm going to be sick.",
         TRUNK_SUMMER = "That poor creature.",
         TRUNK_WINTER = "That poor creature.",
         TURF_CARPETFLOOR = "It's surprisingly scratchy.",
         TURF_CHECKERFLOOR = "These are carved rather well.",
         TURF_DIRT = "A chunk of ground.",
         TURF_FOREST = "A chunk of ground.",
         TURF_GRASS = "A chunk of ground.",
         TURF_MARSH = "A chunk of ground.",
         TURF_ROAD = "Hastily cobbled stones.",
         TURF_ROCKY = "A chunk of ground.",
         TURF_SAVANNA = "A chunk of ground.",
         TURF_WOODFLOOR = "These are floorboards.",
         TURKEYDINNER = "Sorry...",
         TWIGS = "Twigs. I'm saved.",
         UMBRELLA = "Summer rains, you can never predict them.",
         UNIMPLEMENTED = "It doesn't look finished! It could be dangerous.",
         WAFFLES = "I don't even want to know.",
         WALL_HAY = "It blocks wind, but not much else.",
         WALL_HAY_ITEM = "Well aren't I a regular fortification expert.",
         WALL_STONE = "This looks good, actually.",
         WALL_STONE_ITEM = "Because this wall is so useful laying around.",
         WALL_RUINS = "An ancient wall piece.",
         WALL_RUINS_ITEM = "I wonder if the Oni had walls like this.",
         WALL_WOOD = "A palisade. Slightly less useless than hay walls.",
         WALL_WOOD_ITEM = "Glorified sticks.",
         WALRUS = "The worst kind of parent, exposing its child to such violence!",
         WALRUSHAT = "I think a whisker is poking my scalp.",
         WALRUS_CAMP =
            {
               EMPTY = "Was Koishi here?",
               GENERIC = "This is a violent place.",
            },
         WALRUS_TUSK = "This is what I think of your parenting...",
         WASPHIVE = "It's designed for the whole hive to pour out at once.",
         WETGOOP = "Culinary genius.",
         WINTERHAT = "It looks like something Koishi would like.",
         WINTEROMETER = 
            {
               GENERIC = "I can feel if it's hot or cold myself, thanks.",
               BURNT = "It appears to be hot. Just a bit.",
            },
         WORMHOLE =
            {
               GENERIC = "The creatures here are strange.",
               OPEN = "I have a sudden compulsion to jump.",
            },
         WORMHOLE_LIMITED = "Smells like rot. I think it's infected with something.",
         ACCOMPLISHMENT_SHRINE = "I want to use it, and I want the world to know what I did.",        
         LIVINGTREE = "That's certainly not intentional at all.",
         ICESTAFF = "I suppose I'm an ice mage now.",
      },
}
